---
- name: add requiremensts - ubuntu
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Add signed key - ubuntu
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add repository - ubuntu - {{ansible_distribution_release}}
  apt_repository:
    repo: https://deb.nodesource.com/node_{{ NODEJS_VERSION }} 14.x {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution == 'Ubuntu'
