---
- name: install nginx from package - ubuntu
  apt:
    name:
      - nginx
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'


- name: ensure nginx is enabled to start at boot
  systemd:
    name: nginx
    enabled: yes
